name: Android client CI
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          # spotless 8.0.0 requires Java 17
          java-version: '17'

      - name: Build
        run: |
          cd android-client
          ./gradlew assembleDebug
      
      - name: Format
        run: |
          cd android-client
          ./gradlew spotlessCheck

      - name: Lint
        run: |
          cd android-client
          ./gradlew lint
      
      - name: Codespell
        run: |
          brew install codespell
          codespell android-client/app/src/
