name: iOS client CI
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        run: |
          cd ios-client
          xcodebuild build \
            -scheme ios-client \
            -derivedDataPath build \
            -destination 'platform=iOS Simulator,name=iPhone 16'
      
      - name: Format Objective-C
        run: |
          brew install clang-format
          find ios-client/ -name "*.m" -o -name "*.h" | xargs clang-format --dry-run --Werror

      - name: Analyze Objective-C
        run: |
          cd ios-client
          xcodebuild analyze \
            -scheme ios-client \
            -destination 'platform=iOS Simulator,name=iPhone 16'
            GCC_TREAT_WARNINGS_AS_ERRORS=YES
      
      - name: Codespell
        run: |
          brew install codespell
          codespell ios-client/
